### ISSUE TITLE
seek_num 问题

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#11]
ETH 和usdt seek_num获取到的区块高度与浏览器上获取到的不符合   https://ethgasstation.info/api/ethgasAPI.json

比如获取到的 seek_num：9944786  ，erc20_seek_num：9929302    区块链浏览器上看到的区块高度是 11168788

这有什么影响吗？

**Comment by moremorefun** [comment]
seek_num含义是冲币检测到的区块数，这代表程序检测冲币还没检测到最新区块

**Comment by moremorefun** [comment]
另外这个链接
https://ethgasstation.info/api/ethgasAPI.json
是获取推荐的gaprice的，不是获得最新区块数的，与seek_num无关

**Comment by lip5201** [comment]
目前的区块高度是 11175180   那如果在11175180上收到一笔转账   seek_num现在还在9944786那里检测  是不是就意味着 系统检测不到这笔刚转账的交易

**Comment by moremorefun** [comment]
> 目前的区块高度是 11175180 那如果在11175180上收到一笔转账 seek_num现在还在9944786那里检测 是不是就意味着 系统检测不到这笔刚转账的交易

是的

**Comment by lip5201** [comment]
seek_num 或许有bug  ，数据库的记录 seek_num 9973283  ，erc20_seek_num 9974414，使用https://mainnet.infura.io/v3/的接口 获取到的是11176605， 正常来说使用的是 https://mainnet.infura.io/v3/他的api 数据应该同步才对。

**Comment by moremorefun** [comment]
这说明eth的冲币检测刚检测到9973283，erc20的冲币检测刚检测到9974414
还没有追上最新的区块数
单从数字上看没什么问题
如果你确认9973283-11176605这部分区块没有冲币入账条目
可以选择直接停掉程序，手动设置数据库中seek_num到最新的区块数就可以了
