### ISSUE TITLE
冷热钱包问题

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#13]
已知 t_app_config_str 表 
 cold_wallet_address // eth 冷钱包地址
hot_wallet_address // eth 热钱包地址
fee_wallet_address // erc20 零钱整理手续费 热钱包地址
fee_wallet_address_list // erc20 零钱整理手续费 热钱包地址 列表

那么 t_app_config_token 表的
cold_address //冷钱包地址
hot_address//热钱包地址

这两个字段的地址的存在是起什么作用

**Comment by moremorefun** [comment]
t_app_config_token.cold_address 该行token的冷钱包地址
t_app_config_token.hot_address 该行token的热钱包地址
