### ISSUE TITLE
hot_wallet_address 热钱包

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#14]
通过测试发现 币打进了后 会自动转币到冷钱包，
 hot_wallet_address这个热钱包你设计的时候的思路是什么样的。
因为我发现 通过提现api提币的话 是从这个热钱包转账的，hot_wallet_address这个只能有一个地址，而且冲进了来的币并没有转入到这个热钱包当中。那么既然没有币转进这个地址，那为什么提币的话是从 hot_wallet_address这个热钱包地址转呢？这不是很合理啊！能说说你设计这个的思路吗？

**Comment by moremorefun** [comment]
这样设计的原因是：
1. 用户冲进来的资产归集到冷钱包，避免万一系统被黑，用户冲进来的资产被转走。
2. 提币的资产从热钱包出，热钱包中的钱是手动从冷钱包转入的，用来控制可提币数量，避免提币接口万一被黑导致的无限提币。
