### ISSUE TITLE
btc 必须搭建本地节点吗？

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#15]
我测试了几个api    https://blockstream.info/api/  ，https://btc.com/api-doc#Unspent

但是都没有更新任何数据 也没有错误提示，不知道btc是不是一定要搭建本地的节点并开启rpc  才能使用？

**Comment by moremorefun** [comment]
btc节点需要自己搭建，需要使用omni layer的节点服务程序
https://www.omnilayer.org/download.html
