### ISSUE TITLE
冷热钱包问题

### ISSUE THREAD

**Issue by bigcxp** [moremorefun/go-dc-wallet#16]
1.eth的冷热钱包地址与token的冷热钱包地址可以使用相同的吗
2.用户如果需要提币，必须自己先充值eth作为提币手续费吗，可不可以将提币所需的eth换算成usdt,然后交易所为这笔转账付eth,用户只付usdt就可以了

**Comment by moremorefun** [comment]
1. 可以相同
2. 不可以，erc20的手续费必须是eth

**Comment by lip5201** [comment]
关于用户的 erc20的手续费地址 程序里只有一个总的扣费地址 并没有每个用户都有专属的扣费地址！

**Comment by moremorefun** [comment]
是的，这个零钱整理的手续费由平台方承担

**Comment by moremorefun** [comment]
你可以发现在交易所提币的时候，比如你提100usdt，会扣除你10usdt的手续费，那么这10usdt就是他估算的提币手续费+零钱整理手续费的成本.

当然，实际使用一般没这么多

**Comment by lip5201** [comment]
erc20_gas_use  这个值 是扣除usdt提现的费用 需要设置的吗？

**Comment by moremorefun** [comment]
这个是一笔erc20交易的gas使用值的上限值，一般不需要更改，使用默认值就可以
