### ISSUE TITLE
EOS问题

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#17]
1.eos生成用户名  不符合创建规则 
2.eos检测不到交易 我使用的是测试网络测试的 https://jungle3.cryptolions.io

**Comment by moremorefun** [comment]
eos不使用地址作为分辨用户入账的依据，使用的是交易的memo字段，请参考币安的eos冲币流程

因为创建eos地址是需要付费的

**Comment by lip5201** [comment]
交易的memo字段 要填写什么 才能检测到交易呢？

**Comment by moremorefun** [comment]
获取地址接口得到的 
address 为 memo 字段
eos_address 为eos的冲币地址
