### ISSUE TITLE
提示这个错误 没找到原因

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#2]
2020-09-27T15:02:02.178+0800    FATAL   app/env.go:51   read env from .env err: [*errors.errorString] Can't separate key from value
exit status 1

**Comment by moremorefun** [comment]
看起来是.env文件格式不正确

**Comment by lip5201** [comment]
如何修改呢？

**Comment by moremorefun** [comment]
可能windows和mac的换行符不兼容，
如果.env乱码的话，直接把github上的env的内容复制到本地文件里再修改就可以。

**Comment by jetking** [comment]
把 `.env-example` 中双斜杠注释(`//`) 改为 `#` 应该就可以了

**Comment by moremorefun** [comment]
> 把 `.env-example` 中双斜杠注释(`//`) 改为 `#` 应该就可以了

也有可能是mac,windows两个系统换行符不兼容的问题

**Comment by moremorefun** [comment]
> 把 `.env-example` 中双斜杠注释(`//`) 改为 `#` 应该就可以了

看了一下源码，确实是#开头的行才被识别为注释行
