### ISSUE TITLE
heth/eth.go:908	err: [*errors.errorString] not found

### ISSUE THREAD

**Issue by miaoxn** [moremorefun/go-dc-wallet#20]
发送交易好像失败了，用的infura节点，数据库显示send，实际上并没有发送交易数据

**Comment by moremorefun** [comment]
查看数据库的send行的txid
然后在区块链浏览器上查看是否已经发送,但是还没有上链

**Comment by miaoxn** [comment]
区块浏览器查不到数据，应该是没有发送成功

**Comment by miaoxn** [comment]
0x11bbb74c00998b824ff7dc6d2d5ee5b33ffcab5fd9b4b3253a803589bd610bda

**Comment by moremorefun** [comment]
把这个txid的hex的字符串手动发送一下,看看是返回什么信息
