### ISSUE TITLE
设置热钱包私钥问题

### ISSUE THREAD

**Issue by songning4** [moremorefun/go-dc-wallet#21]
请问一下，在用户提现时不是走热钱包转账吗，但是没有提到BTC/ETH/USDT的热钱包私钥设置，请问一下，热钱包私钥在哪里设置？谢谢！

**Comment by songning4** [comment]
看了代码逻辑后发现私钥是从t_address_key里读取，那就是热钱包地址仅限本服务生成的地址，虽然问题解决了，但觉得有点局限性

**Comment by moremorefun** [comment]
以eth为例,
生成交易的时候需要使用热钱包地址的nonce,
如果用外部地址作为热钱包,这个nonce有可能会冲突,导致提币交易出问题.
所以
1. 不提倡热钱包从外部生成
2. 不提倡热钱包地址在外部使用

**Comment by songning4** [comment]
@moremorefun 感谢回复，这确实是安全性和系统考虑
