### ISSUE TITLE
回调时怎么区分代币和主币

### ISSUE THREAD

**Issue by songning4** [moremorefun/go-dc-wallet#23]
在阅读文档和代码的时候产生疑问，ETH使用的地址和ERC20-USDT使用的是同一个地址，BTC和OMNI-USDT使用的也是同一个地址，回调接口中有地址address、币类型symbol。

1、回调接口的币类型symbol有哪些值，能方便罗列出来吗？
平台方便根据这些值做区分

**Comment by moremorefun** [comment]
symbol 包含主链的 eth btc eos
另外代币的是在数据库里自行添加的,所以无法穷尽

**Comment by songning4** [comment]
> symbol 包含主链的 eth btc eos
> 另外代币的是在数据库里自行添加的,所以无法穷尽

感谢回复，我在测试中发现代币返回的symbol其实应该是t_app_config_token里的token_symbol或者t_app_config_token_btc里的token_symbol
