### ISSUE TITLE
关于EOS生成地址的问题

### ISSUE THREAD

**Issue by songning4** [moremorefun/go-dc-wallet#24]
运行了go run cmd/db/main.go后打印了SQL，将SQL导入库后执行go run cmd/dbinit/main.go后，数据库中填充了很多数据，t_address_key中也填充了很多地址和密钥，可是关于EOS的地址很奇怪，是这样的：

![1](https://user-images.githubusercontent.com/65797035/104994178-fc39bc80-5a5e-11eb-95a0-e7dc2a47fd2d.png)

101	eos	1000000001		1
102	eos	1000000002		1
103	eos	1000000003		1
104	eos	1000000004		1
105	eos	1000000005		1
106	eos	1000000006		1
107	eos	1000000007		1
108	eos	1000000008		1
109	eos	1000000009		1
110	eos	1000000010		1
111	eos	1000000011		0
112	eos	1000000012		0
113	eos	1000000013		0
114	eos	1000000014		0
115	eos	1000000015		0
116	eos	1000000016		0
117	eos	1000000017		0
118	eos	1000000018		0
119	eos	1000000019		0
120	eos	1000000020		0
121	eos	1000000021		0
122	eos	1000000022		0
123	eos	1000000023		0
124	eos	1000000024		0
125	eos	1000000025		0
126	eos	1000000026		0
127	eos	1000000027		0
128	eos	1000000028		0
129	eos	1000000029		0

我通过其他钱包生成的地址是这样的：0xA585B68a9A4F912C72B85e3F49120C2d8f9C0754

![2](https://user-images.githubusercontent.com/65797035/104994321-34d99600-5a5f-11eb-993c-bb9381d36e2c.png)

请问一下go-dc-wallet是不是对地址做了特殊处理，或者有什么问题存在吗？

**Comment by moremorefun** [comment]
eos于其他链不同,因为eos创建地址需要支付eos费用
所以eos的充币使用memo区分
这里的eos地址实际上是分配的memo字符串

**Comment by songning4** [comment]
> eos于其他链不同,因为eos创建地址需要支付eos费用
> 所以eos的充币使用memo区分
> 这里的eos地址实际上是分配的memo字符串

好的，谢谢

**Comment by moremorefun** [comment]
另外eos的seek写的不好,很可能跟不上最新的区块数
建议换一种根据地址seek的方法

**Comment by songning4** [comment]
> 另外eos的seek写的不好,很可能跟不上最新的区块数
> 建议换一种根据地址seek的方法

谢谢老师，目前已经放弃EOS了
