### ISSUE TITLE
项目看着挺不错 可以联系啊能付费定制和完善吗

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#3]

**Comment by moremorefun** [comment]
具体有什么需求呢？

**Comment by lip5201** [comment]
按照你目前的描述 我需求是在你现有的基础上检查下bug并完善   然后把安全方面做好 另外加一个会员管理的图形界面！有QQ吗 可以联系吗

**Comment by moremorefun** [comment]
邮箱联系我吧

**Comment by lip5201** [comment]
能收到吗？ 我觉得你项目不错！想定制 具体就是加一个前后端 可以方便管理





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "moremorefun/go-dc-wallet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 下午3:30
收件人:&nbsp;"moremorefun/go-dc-wallet"<go-dc-wallet@noreply.github.com&gt;;
抄送:&nbsp;"李鹏"<87313957@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [moremorefun/go-dc-wallet] 项目看着挺不错 可以联系啊能付费定制和完善吗 (#3)





 
邮箱联系我吧

**Comment by lip5201** [comment]
能收到吗？ 我觉得你项目不错！想定制 具体就是加一个前后端 可以方便管理！如果可以定制 你可以报下价格





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "moremorefun/go-dc-wallet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 下午3:30
收件人:&nbsp;"moremorefun/go-dc-wallet"<go-dc-wallet@noreply.github.com&gt;;
抄送:&nbsp;"李鹏"<87313957@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [moremorefun/go-dc-wallet] 项目看着挺不错 可以联系啊能付费定制和完善吗 (#3)





 
邮箱联系我吧

**Comment by moremorefun** [comment]
没有收到邮件，github上可以查到我的gmail地址
