### ISSUE TITLE
API接口协议中包含字段nonce，主要保证签名不可预测。 这个nonce值是怎么来的

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#4]
https://www.jidangeng.com/2020/04/21/eth-wallet-api-address/#more
在使用获取冲币地址的情况下  需要传输nonce这个参数，那这个nonce参数值是怎么来的？网站上的说明  没看懂怎么来设置这个值。

**Comment by moremorefun** [comment]
api调用端直接用uuid生成就可以
