### ISSUE TITLE
关于 USDT地址 公钥和私钥的问题

### ISSUE THREAD

**Issue by lip5201** [moremorefun/go-dc-wallet#6]
1.程序里看到生成私钥，那么公钥在哪里，可以自己去修改公钥吗？
2.可以生成usdt地址吗？ 在程序里没看到可以生成usdt的地方，生成的地址都是eth eos和btc

**Comment by moremorefun** [comment]
1. 公钥匙根据私钥计算出来了，不需要储存
2. usdt分为omni-usdt和erc20-usdt，分别对应btc的地址和eth的地址
